// <auto-generated />
using FastFoodStore.DAL.DB.Providers.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodStore.DAL.DB.Providers.SqLite.Migrations
{
    [DbContext(typeof(ContextDataObjectsSqliteDB))]
    partial class ContextDataObjectsSqliteDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FastFoodStore.DAL.Models.ProductMDAL", b =>
                {
                    b.Property<int>("ProductMDALId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MDAL_Product_Descriptiont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MDAL_Product_ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MDAL_Product_IsAvailability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MDAL_Product_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MDAL_Product_Price")
                        .HasColumnType("REAL");

                    b.Property<int>("MDAL_Product_PurchasedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MDAL_Product_Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductMDALId");

                    b.ToTable("ProductsMDAL");
                });
#pragma warning restore 612, 618
        }
    }
}
